### ISSUE TITLE
MultiCol-SLAM Ubuntu 14.04 Build Error

### ISSUE THREAD

**Issue by ardalanK** [urbste/MultiCol-SLAM#13]
Hi,

I am trying to build the MultiCol-SLAM on Ubuntu 14.04 but am getting the error below. Do you have any suggestions how to fix it?

------------------------------------------------------------------------------------
In file included from /home/ardalan/ORB-Fisheye/MultiCol-SLAM/src/g2o_MultiCol_sim3_expmap.cpp:20:0:
/home/ardalan/ORB-Fisheye/MultiCol-SLAM/include/g2o_MultiCol_sim3_expmap.h:117:22: error: expected ‘)’ before ‘<’ token
    std::unordered_map<size_t, int>& kp_to_cam1,
                      ^
/home/ardalan/ORB-Fisheye/MultiCol-SLAM/include/g2o_MultiCol_sim3_expmap.h:175:3: error: ‘unordered_map’ in namespace ‘std’ does not name a type
   std::unordered_map<size_t, int> keypoint_to_cam1;
   ^
/home/ardalan/ORB-Fisheye/MultiCol-SLAM/include/g2o_MultiCol_sim3_expmap.h:176:3: error: ‘unordered_map’ in namespace ‘std’ does not name a type
   std::unordered_map<size_t, int> keypoint_to_cam2;
   ^
/home/ardalan/ORB-Fisheye/MultiCol-SLAM/include/g2o_MultiCol_sim3_expmap.h: In member function ‘cv::Vec2d MultiColSLAM::VertexSim3Expmap_Multi::cam_map1(const Vector3d&, int) const’:
/home/ardalan/ORB-Fisheye/MultiCol-SLAM/include/g2o_MultiCol_sim3_expmap.h:142:17: error: ‘keypoint_to_cam1’ was not declared in this scope
    int camIdx = keypoint_to_cam1.find(ptIdx)->second;
                 ^
/home/ardalan/ORB-Fisheye/MultiCol-SLAM/include/g2o_MultiCol_sim3_expmap.h: In member function ‘cv::Vec2d MultiColSLAM::VertexSim3Expmap_Multi::cam_map2(const Vector3d&, int) const’:
/home/ardalan/ORB-Fisheye/MultiCol-SLAM/include/g2o_MultiCol_sim3_expmap.h:153:17: error: ‘keypoint_to_cam2’ was not declared in this scope
    int camIdx = keypoint_to_cam2.find(ptIdx)->second;
                 ^
/home/ardalan/ORB-Fisheye/MultiCol-SLAM/src/g2o_MultiCol_sim3_expmap.cpp: At global scope:
/home/ardalan/ORB-Fisheye/MultiCol-SLAM/src/g2o_MultiCol_sim3_expmap.cpp:25:48: error: expected constructor, destructor, or type conversion before ‘(’ token
  VertexSim3Expmap_Multi::VertexSim3Expmap_Multi(
                                                ^
make[2]: *** [CMakeFiles/MultiCol-SLAM.dir/src/g2o_MultiCol_sim3_expmap.o] Error 1
make[1]: *** [CMakeFiles/MultiCol-SLAM.dir/all] Error 2
make: *** [all] Error 2
--------------------------------------------------------------------------------------------

Thanks,
Ardalan

**Comment by oya123** [comment]
I have the same problem as you, how did you solve it?

**Comment by Mosquito19** [comment]
I have the same problem as you, how did you solve it?
-　Ｍe too!!!!!-

**Comment by KhazixW2** [comment]
i guess the problem that the soft version have a conflict  about   two or three soft version confilct .

because , when you use a native environment  example vmware or virsual box .the problem don't found.
