### ISSUE TITLE
Coordinate frame

### ISSUE THREAD

**Issue by geokarant** [urbste/MultiCol-SLAM#3]
Hello urbste and thank you for sharing your great work!

I would like to ask you where in the code can i see which reference frame is used.

In which coordinates did you get the camera pose and how do you translate and rotate them in order to move to the camera coordinate frame? Thanks in advance!

**Comment by urbste** [comment]
I'm not really sure what you are asking.
The reference frame is the first pose which is initialized with an identity matrix.
