### ISSUE TITLE
How to build the "vocabulary file" for my project

### ISSUE THREAD

**Issue by zhangcaocao** [urbste/MultiCol-SLAM#39]
Dear Author, I want to know How to build the "vocabulary file" for my project ?

**Comment by zhangcaocao** [comment]
Oh I get it

**Comment by zhangcaocao** [comment]
https://github.com/raulmur/ORB_SLAM/issues/13

**Comment by zhangcaocao** [comment]
Oh I get it : 
https://github.com/raulmur/ORB_SLAM/issues/13

**Comment by manthan99** [comment]
Have a look at this repo for step by step procedure to create your own vocabulary:
https://github.com/manthan99/ORB_SLAM_vocab-build
