### ISSUE TITLE
How to run this whole porject smoothly?

### ISSUE THREAD

**Issue by TengFeiHan0** [urbste/MultiCol-SLAM#40]
Dear @FookSong 
I have downloaded and compiled this project very quickly, then I try to run this program. When executing  ``./Examples/Lafida/multi_col_slam_lafida ./Examples/small_orb_omni_voc_9_6.yml ./Examples/Lafida/Slam_Settings_indoor2.yaml ./Examples/Lafida/Calibration/ /home/mm/Downloads/indoor_dynamic`

`The viewer window has disappeared after one second.
![Screenshot from 2019-07-04 20-13-46](https://user-images.githubusercontent.com/38068286/60666964-f25f6100-9e9a-11e9-9b16-ca1e052df7ee.png)
what is the confusing thing is that I didn't change any source files, would you please to share your running steps or give me some suggestions?

**Comment by hddgi** [comment]
Hi, Could you please tell me how do you fix this problem?

**Comment by liuyl12** [comment]
I met with the same problem and pls tell me how to solve it...

**Comment by liuyl12** [comment]
> Dear @FookSong
> I have downloaded and compiled this project very quickly, then I try to run this program. When executing ``./Examples/Lafida/multi_col_slam_lafida ./Examples/small_orb_omni_voc_9_6.yml ./Examples/Lafida/Slam_Settings_indoor2.yaml ./Examples/Lafida/Calibration/ /home/mm/Downloads/indoor_dynamic`
> 
> `The viewer window has disappeared after one second.
> ![Screenshot from 2019-07-04 20-13-46](https://user-images.githubusercontent.com/38068286/60666964-f25f6100-9e9a-11e9-9b16-ca1e052df7ee.png)
> what is the confusing thing is that I didn't change any source files, would you please to share your running steps or give me some suggestions?

@TengFeiHan0 hello, could you share your solution?

**Comment by KhazixW2** [comment]
the problem maybe is soft version conflict .
