### ISSUE TITLE
How to generate the Jacobian matrix？

### ISSUE THREAD

**Issue by yangtzey** [urbste/MultiCol-SLAM#46]
The function mcsJacs1 in g2o_MultiCol_vertices_edges.cpp file.
The code seems to be generated using a tool. What tool did you use to generate the code?
thank you very much!

**Comment by urbste** [comment]
Hi.
I used Matlab's Symbolic toolbox to generate them.

Am Do., 21. Jan. 2021 um 13:06 Uhr schrieb yangtzey <
notifications@github.com>:

**Comment by yangtzey** [comment]
thank you

**Comment by yangtzey** [comment]
Could you open source the Matlab code that the part of calculating the Jacobian?
thank you soooooooo much!
