### ISSUE TITLE
Multi-Col SLAM for ORB-SLAM3

### ISSUE THREAD

**Issue by balasubramani0395** [urbste/MultiCol-SLAM#51]
I have worked with Multi-Col SLAM. It is really useful for our development I am wondering if you have created any package to work with multiple cameras in ORB-SLAM3?

**Comment by urbste** [comment]
Hi. Sorry no, MultiCol-Slam was developed during my time as a phd. Orb-slam 3 did not exist back then.

**Comment by balasubramani0395** [comment]
Hi, We are planning to develop it for us.  Would you like to join us in the development?

**Comment by Alex-Beh** [comment]
@balasubramani0395 Hi, may I have your contact method? I am interested and would like to know your experience on ORBSLAM3

**Comment by KhazixW2** [comment]
@Alex-Beh  @balasubramani0395 @urbste  hi , everybody ， I have some problem about orbslam3 for mutil camera version.

**Comment by balasubramani0395** [comment]
@Alex-Beh @KhazixW2  https://www.linkedin.com/in/balasubramani-velliyangiri-393bb8b5.  Please contact me in linkedin. Let's discuss

**Comment by KhazixW2** [comment]
> hello ，the link have a error.  maybe have a long time, it is light off.

**Comment by WuZihao12** [comment]
Hello, I plan to study a multi-camera system based on ORB-SLAM3, how is your current research progress?

**Comment by WuZihao12** [comment]
@balasubramani0395 Hello, I plan to study a multi-camera system based on ORB-SLAM3, how is your current research progress?

**Comment by Alex-Beh** [comment]
@WuZihao12 I am still interested to this topic. Can you send me your contact? So we can discuss further

**Comment by urbste** [comment]
Hi guys. I am not doing any research in this field anymore. You are on your own ;)

**Comment by FreedomRings** [comment]
That makes me sad – you are clearly quite good at this.

**Comment by WuZihao12** [comment]
@Alex-Beh Ok，my email is zihaowu.247@gmail.com. After communicating via email, you can obtain their respective contact information
