### ISSUE TITLE
multicamera calibration?

### ISSUE THREAD

**Issue by antithing** [urbste/MultiCol-SLAM#7]
Hi, can you explain the necessary calibration process for me please? I can calibrate each camera separately using the info and links you provide, but how should I get the extrinsics between cameras?

Do I need to do this, as I would with a stereo based system? Or do i just calibrate each camera separately?

Thank you again for the code! :)

**Comment by antithing** [comment]
Thanks!  I am on windows without ROS, but will try to get MCPTAM running, or get a linux install just for calibration. :) Thanks again for making your code available.

**Comment by urbste** [comment]
No problem. Sorry that I can not provide any working calibration code, that is easy to use. But that was not the focus of my research.
I hope you can get it running.
Cheers, Steffen

**Comment by antithing** [comment]
Hi, sorry to bother you again, I am putting together a 5-camera rig, the images from which are not quite as 'fisheye' as the ones in the demo images. (Please see below) 
Once calibrated, would these work with your code? Or would I need to adjust some parameters to have it running? 

![sensor1](https://cloud.githubusercontent.com/assets/11506730/20982882/319fe36c-bcb2-11e6-89b3-3a6fb2ed2331.png)

**Comment by FreedomRings** [comment]
@antithing - Did you ever get MCPTAM calibration running on Windows?  Tips?

**Comment by antithing** [comment]
Hi there. i did not. It is heavily bound into a linux workspace. I did get a calibration working though, using this:

https://sites.google.com/site/prclibo/toolbox/doc

**Comment by FreedomRings** [comment]
@antithing - I had the same problem - I also used a MatLab function (not this one) which did not work well for multiple cameras.  I am writing a C++ program Frankensteined from other projects and I am missing one element that is not in your solution either.  Those stinking 3 Affine parameters:  c, d, and e.  I cannot figure out how to calculate them, or even if I need to.  Your solution does not seem to create them either.  I am soooooo befuddled and cannot seem to find any code to calibrate the Affine parameters.  

Any insights would be really helpful!

**Comment by dzy130120** [comment]
@antithing i have three fish-eye cameras whose directions differ from each other by 120°, is the toolbox ,https://sites.google.com/site/prclibo/toolbox/doc ,suitable  for my cameras?
