### ISSUE TITLE
Another calibration question...

### ISSUE THREAD

**Issue by antithing** [urbste/MultiCol-SLAM#8]
Hi, sorry to bother you again. I have found a multi-camera calibration toolbox, that gives me the following result:

Extrinsics: 
```
Camera #1 :
1  0  0  0
0  1  0  0
0  0  1  0
0  0  0  1
```

Camera #2 :
```
 0.4609181  -0.009186284    -0.8873951     -303.5744
0.03479596     0.9993646   0.007727831      23.35298
 0.8867603   -0.03443966     0.4609448     -163.4985
         0             0             0             1
```
Camera #3 :
```
 -0.7048325     0.1634035     0.6902974      333.0892
-0.02166609     0.9676953      -0.25119     -86.11362
 -0.7090429    -0.1920029    -0.6785227      -465.258
          0             0             0             1
```
Camera #4 :
```
  0.5077068    -0.0381636     0.8606842      375.7625
-0.08449859     0.9919959    0.09383074     -4.202368
 -0.8573761    -0.1203651     0.5004183     -113.0211
          0             0             0             1
```
Camera #5 :
```
-0.748888   -0.05602026    -0.6603246     -143.0585
0.1751792     0.9442421    -0.2787815     -114.4791
0.6391237    -0.3244512    -0.6973179      -515.224
        0             0             0             1
```

In the file `MultiCamSys_Calibration.yaml`, the content is:

`# camera back
CameraSystem.cam1_1: -0.0238361786473007   #r1
CameraSystem.cam1_2: -2.05998171167958     #r2
CameraSystem.cam1_3: 0.695126790868671     #r3
CameraSystem.cam1_4: -0.140202124607334    #t1
CameraSystem.cam1_5: 0.0219677971160655    #t2
CameraSystem.cam1_6: -0.0226322662838432   #t3
# camera right    
CameraSystem.cam2_1: -0.0103943566650926   #r1
CameraSystem.cam2_2: 1.12505249943085      #r2
CameraSystem.cam2_3: -0.402901183146028    #r3
CameraSystem.cam2_4: 0.108753418890423     #t1
CameraSystem.cam2_5: 0.0636197216520153    #t2
CameraSystem.cam2_6: 0.0657911760105832    #t3
# camera left    
CameraSystem.cam3_1: 0                    #r1
CameraSystem.cam3_2: 0                    #r2
CameraSystem.cam3_3: 0                    #r3
CameraSystem.cam3_4: -0.00157612288268783 #t1
CameraSystem.cam3_5: 0.103615531247527    #t2
CameraSystem.cam3_6: 0.201416323496156    #t3`

I can just add the translation values from my extrinsic matrices, but what are the `#r` values? Radians? 

Thank you again! (the toolbox, in case you are interested, is: https://sites.google.com/site/prclibo/toolbox).

**Comment by LuSiYing** [comment]
I guess you should use function **hom2cayle**y in include/misc.h to transform a 4x4 matrix to a 6x1 vector which represents (r1, r2, r3, t1, t2, t3)

**Comment by antithing** [comment]
Thank you! That is exactly what I need.
